# åŸºæœ¬ä¿¡æ¯
baseURL = "https://oxygenbytes.github.io" # ç»‘å®šçš„åŸŸå
languageCode = "zh-en" # è¯­è¨€
title = "Zxq's Site" # ç«™ç‚¹åç§°
theme = "PaperMod" # ä¸»é¢˜åå­—ï¼Œå’Œthemesæ–‡ä»¶å¤¹ä¸‹çš„ä¸€è‡´

# åŸºæœ¬é…ç½®
enableInlineShortcodes = true # å…è®¸å†…è”çŸ­ç 
enableEmoji = true # å…è®¸ä½¿ç”¨ Emoji è¡¨æƒ…ï¼Œå»ºè®® true
enableRobotsTXT = true # å…è®¸çˆ¬è™«æŠ“å–åˆ°æœç´¢å¼•æ“ï¼Œå»ºè®® true
hasCJKLanguage = true # è‡ªåŠ¨æ£€æµ‹æ˜¯å¦åŒ…å« ä¸­æ–‡æ—¥æ–‡éŸ©æ–‡ å¦‚æœæ–‡ç« ä¸­ä½¿ç”¨äº†å¾ˆå¤šä¸­æ–‡å¼•å·çš„è¯å¯ä»¥å¼€å¯
buildDrafts = false
buildFuture = false
buildExpired = false
paginate = 15 # æ¯é¡µæ˜¾ç¤ºçš„æ–‡ç« æ•°
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[minify]
disableXML = true

[permalinks]
post = "/:title/"

[languages.en]
languageName = "English"
weight = 1

  [languages.en.profileMode]
  enabled = true
  subtitle = '''Stay Hungry, Stay Foolish. \
  See Different, Think Different. '''
  imageUrl = "avatar.jpeg"
  imageWidth = 150
  imageHeight = 150

    [[languages.en.profileMode.buttons]]
    name = "ğŸ“šåšæ–‡"
    url = "posts"

    [[languages.en.profileMode.buttons]]
    name = "ğŸ‘¨ğŸ»â€ğŸ’»Leetcode"
    url = "leetcode"

    [[languages.en.profileMode.buttons]]
    name = "ğŸ–å‰‘æŒ‡offer"
    url = "swordoffer"

[[languages.en.menu.main]]
identifier = "home"
name = "ğŸ ä¸»é¡µ"
url = "/"
weight = 1

[[languages.en.menu.main]]
identifier = "search"
name = "ğŸ”æœç´¢"
url = "search"
weight = 2

[[languages.en.menu.main]]
identifier = "posts"
name = "ğŸ“šæ–‡ç« "
url = "posts"
weight = 3

[[languages.en.menu.main]]
identifier = "archives"
name = "â±æ—¶é—´è½´"
url = "archives/"
weight = 20

[[languages.en.menu.main]]
identifier = "tags"
name = "ğŸ”–æ ‡ç­¾"
url = "tags"
weight = 40

[[languages.en.menu.main]]
identifier = "about"
name = "ğŸ™‹ğŸ»â€â™‚ï¸å…³äº"
url = "about"
weight = 50

# [[languages.en.menu.main]]
# identifier = "links"
# name = "ğŸ¤å‹é“¾"
# url = "links"
# weight = 60

[outputs]
home = [ "HTML", "RSS", "JSON" ]

[params]
disableThemeToggle = false
DateFormat = "2006-01-02"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
hideFooter = false
ShowWordCounts = true
VisitCount = true
ShowLastMod = true
ShowToc = true
TocOpen = true
comments = true

  # Social icons
  [[params.socialIcons]]
    name = "github"
    url  = "https://github.com/oxygenbytes"

  [[params.socialIcons]]
    name = "email"
    url  = "mailto:oxygenbytes@gmail.com"

  [[params.socialIcons]]
  name = "wechat"
  url = "WechatIMG4.jpeg"
